import UIKit
import SwiftUI
import ShapeCore

/// 1枚の診断書PDF風画像を生成する（暫定版）
final class ReportGenerator {

    static func generate(from data: ReportData) -> UIImage {

        let width: CGFloat = 1600
        let height: CGFloat = 2300
        
        let renderer = UIGraphicsImageRenderer(size: CGSize(width: width, height: height))
        
        return renderer.image { ctx in
            let context = ctx.cgContext
            
            // 背景
            context.setFillColor(UIColor.white.cgColor)
            context.fill(CGRect(x: 0, y: 0, width: width, height: height))
            
            // タイトル
            let title = "AI姿勢分析レポート"
            let titleAttr: [NSAttributedString.Key : Any] = [
                .font: UIFont.boldSystemFont(ofSize: 46),
                .foregroundColor: UIColor.black
            ]
            title.draw(in: CGRect(x: 60, y: 60, width: width-120, height: 60), withAttributes: titleAttr)
            
            // 日付
            let df = DateFormatter()
            df.dateFormat = "yyyy/MM/dd"
            let dateString = "Date: \(df.string(from: data.date))"
            dateString.draw(in: CGRect(x: 60, y: 130, width: 600, height: 40),
                            withAttributes: [.font: UIFont.systemFont(ofSize: 28),
                                             .foregroundColor: UIColor.darkGray])
            
            // 画像2枚（左右）
            let imgH: CGFloat = 700
            data.capturedImage.draw(in: CGRect(x: 80, y: 200, width: 700, height: imgH))
            data.skeletonImage.draw(in: CGRect(x: 820, y: 200, width: 700, height: imgH))
            
            // スコア
            let scoreStr = "姿勢スコア: \(data.score)/100"
            scoreStr.draw(
                in: CGRect(x: 80, y: 950, width: width-160, height: 60),
                withAttributes: [.font: UIFont.boldSystemFont(ofSize: 42),
                                 .foregroundColor: UIColor.black]
            )
            
            // コメント
            data.message.draw(
                in: CGRect(x: 80, y: 1020, width: width-160, height: 200),
                withAttributes: [.font: UIFont.systemFont(ofSize: 32),
                                 .foregroundColor: UIColor.darkGray]
            )
            
            // 指標テキスト
            let items = [
                "肩の左右差: \(String(format: "%.3f", data.shoulderDiff))",
                "骨盤の左右差: \(String(format: "%.3f", data.hipDiff))",
                "体幹傾き角度: \(String(format: "%.2f°", data.torsoTilt))",
                "頭の位置ずれ: \(String(format: "%.3f", data.headOffset))",
                "膝の左右差: \(String(format: "%.3f", data.kneeDiff))",
                "足首の左右差: \(String(format: "%.3f", data.ankleDiff))"
            ]
            
            var y: CGFloat = 1250
            
            for line in items {
                line.draw(
                    in: CGRect(x: 80, y: y, width: width-160, height: 40),
                    withAttributes: [.font: UIFont.systemFont(ofSize: 30),
                                     .foregroundColor: UIColor.black]
                )
                y += 55
            }
            
            // フッター
            "Generated by ShapeNote".draw(
                in: CGRect(x: 80,
                           y: height - 120,
                           width: width-160,
                           height: 40),
                withAttributes: [.font: UIFont.systemFont(ofSize: 26),
                                 .foregroundColor: UIColor.gray])
        }
    }
}
